#!/usr/bin/env python3
"""Export the frozen dynamic Random Forest to a compact ESP32 C++ header."""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
from pathlib import Path

import joblib
import numpy as np
import pandas as pd


ROOT = Path(__file__).resolve().parents[2]
MODEL_PATH = ROOT / "model" / "hierarchical_dynamic_rf.joblib"
CONFIG_PATH = ROOT / "model" / "hierarchical_model_config.json"
RUNTIME_PATH = ROOT / "inference" / "realtime_inference_ble.py"
HEADER_PATH = (
    ROOT
    / "firmware"
    / "esp32"
    / "MedBox_LiveTrain_AI"
    / "weight_model_generated.h"
)
REPORT_PATH = ROOT / "inference" / "weight" / "esp32_export_report.json"


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as file:
        for block in iter(lambda: file.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def load_runtime_module():
    spec = importlib.util.spec_from_file_location("medbox_weight_runtime", RUNTIME_PATH)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not import runtime module: {RUNTIME_PATH}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def flatten_forest(model):
    roots: list[int] = []
    nodes: list[dict[str, object]] = []

    for estimator in model.estimators_:
        tree = estimator.tree_
        offset = len(nodes)
        roots.append(offset)

        for index in range(tree.node_count):
            left = int(tree.children_left[index])
            right = int(tree.children_right[index])
            feature = int(tree.feature[index])
            if left >= 0:
                left += offset
                right += offset
                probabilities = (0.0, 0.0, 0.0)
            else:
                values = np.asarray(tree.value[index][0], dtype=np.float64)
                total = float(values.sum())
                if total <= 0:
                    raise ValueError(f"Tree leaf {index} has no class weight")
                probabilities = tuple(float(value / total) for value in values)

            nodes.append(
                {
                    "left": left,
                    "right": right,
                    "feature": feature,
                    "threshold": float(tree.threshold[index]) if feature >= 0 else 0.0,
                    "probabilities": probabilities,
                }
            )

    if len(nodes) >= 32768:
        raise ValueError("The flattened forest no longer fits int16 child indices")
    return roots, nodes


def exported_probabilities(roots, nodes, features: np.ndarray) -> np.ndarray:
    probabilities = np.zeros(3, dtype=np.float64)
    for root in roots:
        index = root
        for _ in range(32):
            node = nodes[index]
            feature = int(node["feature"])
            if feature < 0:
                probabilities += np.asarray(node["probabilities"], dtype=np.float32)
                break
            if features[feature] <= float(node["threshold"]):
                index = int(node["left"])
            else:
                index = int(node["right"])
        else:
            raise RuntimeError("Tree traversal exceeded the expected maximum depth")
    return probabilities / len(roots)


def render_header(model, config, roots, nodes) -> str:
    feature_names = list(config["dynamic_features"])
    if list(model.classes_) != ["DISTURBANCE", "NONE", "RETURN"]:
        raise ValueError(f"Unexpected RF class order: {list(model.classes_)}")
    if len(feature_names) != int(model.n_features_in_):
        raise ValueError("Model and configuration feature counts do not match")

    root_lines = []
    for start in range(0, len(roots), 12):
        root_lines.append("    " + ", ".join(str(value) for value in roots[start : start + 12]))

    node_lines = []
    def float_literal(value: float) -> str:
        rendered = f"{np.float32(value):.9g}"
        if "." not in rendered and "e" not in rendered.lower():
            rendered += ".0"
        return rendered + "f"

    for node in nodes:
        p0, p1, p2 = node["probabilities"]
        node_lines.append(
            "    {"
            f"{node['left']}, {node['right']}, {node['feature']}, "
            f"{float(node['threshold']):.17g}, "
            f"{float_literal(p0)}, {float_literal(p1)}, {float_literal(p2)}"
            "}"
        )

    features_comment = "\n".join(
        f"//   {index:2d}: {name}" for index, name in enumerate(feature_names)
    )
    return f"""// Generated by inference/weight/export_esp32_weight_model.py.
// Do not edit by hand; regenerate from the canonical model/ artifacts.
#pragma once

#include <cstddef>
#include <cstdint>
#include <cstring>

#if defined(ARDUINO_ARCH_ESP32)
#include <Arduino.h>
#define MEDBOX_WEIGHT_PROGMEM PROGMEM
#else
#define MEDBOX_WEIGHT_PROGMEM
#endif

namespace medbox_weight_model {{

// Dynamic feature order (must match hierarchical_model_config.json):
{features_comment}

struct RfNode {{
    int16_t left;
    int16_t right;
    int8_t feature;
    double threshold;
    float probability0;
    float probability1;
    float probability2;
}};

static constexpr size_t kFeatureCount = {len(feature_names)};
static constexpr size_t kTreeCount = {len(roots)};
static constexpr size_t kNodeCount = {len(nodes)};

static const uint16_t kTreeRoots[kTreeCount] MEDBOX_WEIGHT_PROGMEM = {{
{',\n'.join(root_lines)}
}};

static const RfNode kNodes[kNodeCount] MEDBOX_WEIGHT_PROGMEM = {{
{',\n'.join(node_lines)}
}};

inline uint16_t readTreeRoot(size_t index) {{
#if defined(ARDUINO_ARCH_ESP32)
    return pgm_read_word(&kTreeRoots[index]);
#else
    return kTreeRoots[index];
#endif
}}

inline RfNode readNode(size_t index) {{
    RfNode node;
#if defined(ARDUINO_ARCH_ESP32)
    memcpy_P(&node, &kNodes[index], sizeof(node));
#else
    std::memcpy(&node, &kNodes[index], sizeof(node));
#endif
    return node;
}}

}}  // namespace medbox_weight_model

#undef MEDBOX_WEIGHT_PROGMEM
"""


def verify(model, config, roots, nodes):
    runtime = load_runtime_module()
    hierarchical_model = runtime.HierarchicalMedicationModel()
    max_probability_error = 0.0
    dynamic_cases = 0
    label_mismatches = []

    for dataset in ("round1", "round2", "synthetic_round3"):
        events = pd.read_csv(ROOT / "data" / dataset / "events.csv")
        samples = pd.read_csv(ROOT / "data" / dataset / "samples.csv")
        for event in events.itertuples():
            rows = samples[samples["event_id"] == event.event_id].sort_values("time_ms")
            event_samples = [
                {"time_ms": int(row.time_ms), "weight_g": float(row.weight_g)}
                for row in rows.itertuples()
            ]
            original = hierarchical_model.predict(
                float(event.before_g), float(event.after_g), event_samples
            )
            if original["stage"] != "DYNAMIC_RF":
                continue

            dynamic_cases += 1
            features = runtime.extract_dynamic_features(float(event.before_g), event_samples)
            vector = np.asarray(
                [features[name] for name in config["dynamic_features"]], dtype=np.float64
            )
            expected = model.predict_proba(pd.DataFrame([features]))[0]
            actual = exported_probabilities(roots, nodes, vector)
            max_probability_error = max(
                max_probability_error, float(np.max(np.abs(expected - actual)))
            )
            actual_label = str(model.classes_[int(np.argmax(actual))])
            if actual_label != original["prediction"]:
                label_mismatches.append(f"{dataset}:{event.event_id}")

    if label_mismatches:
        raise AssertionError(f"Exported forest label mismatches: {label_mismatches}")
    return {
        "datasets": ["round1", "round2", "synthetic_round3"],
        "dynamic_cases": dynamic_cases,
        "label_mismatches": 0,
        "max_probability_error": max_probability_error,
    }


def build_outputs():
    model = joblib.load(MODEL_PATH)
    config = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
    roots, nodes = flatten_forest(model)
    verification = verify(model, config, roots, nodes)
    header = render_header(model, config, roots, nodes)
    report = {
        "format_version": 1,
        "source_model": "model/hierarchical_dynamic_rf.joblib",
        "source_model_sha256": sha256(MODEL_PATH),
        "source_config": "model/hierarchical_model_config.json",
        "source_config_sha256": sha256(CONFIG_PATH),
        "class_order": [str(value) for value in model.classes_],
        "feature_count": int(model.n_features_in_),
        "tree_count": len(roots),
        "node_count": len(nodes),
        "max_tree_depth": max(tree.tree_.max_depth for tree in model.estimators_),
        "verification": verification,
    }
    return header, json.dumps(report, indent=2, sort_keys=True) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail if generated files are stale")
    args = parser.parse_args()

    header, report = build_outputs()
    if args.check:
        stale = []
        if not HEADER_PATH.exists() or HEADER_PATH.read_text(encoding="utf-8") != header:
            stale.append(str(HEADER_PATH.relative_to(ROOT)))
        if not REPORT_PATH.exists() or REPORT_PATH.read_text(encoding="utf-8") != report:
            stale.append(str(REPORT_PATH.relative_to(ROOT)))
        if stale:
            raise SystemExit("Stale generated weight model files: " + ", ".join(stale))
        print("ESP32 weight model artifacts are current.")
        return

    HEADER_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    HEADER_PATH.write_text(header, encoding="utf-8")
    REPORT_PATH.write_text(report, encoding="utf-8")
    print(f"Wrote {HEADER_PATH.relative_to(ROOT)}")
    print(f"Wrote {REPORT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
